# promise

- promise 有3个状态，pending，fullfilled，rejected。一旦有了确定的状态，promise的状态就不能再更改了

  ```javascript
  
  new Promise((resolve, reject) => {
      resove(1)
  	reject(2)// 代码里连着两行resolve 和 reject，在第一次resolve以后就确定状态了，reject就不会走了
  })
  
  ```

- promise 有哪些属性和方法，它们的使用场景是什么

  - all

    数组里的**全部的promise**实例都**成功**返回

  - race

    数组里**某个promise**有确定结果了，**不管是成功还是失败**，就返回了。

    > 某个promise有确定结果了，就会按照这个返回的结果去选择执行race后面的then还是catch
    >
    > **其他的promise并不会取消**，还是会执行完毕

  - allSettled

    数组里的**全部promise**有确定结果了，**不管是成功还是失败**，再返回

  - resolve，reject

  - any

    数组里**任何一个promise成功，就返回**。如果数组里的都失败，那会返回全部失败原因的数据

    

- promise 有什么特殊的地方
	
	- 链式调用promise，一堆then，中间位置插进catch，catch会拦截到前面暴露的error，catch后面的then 会继续正常的走（通过不会这么写）
	- 如果then里面继续生成一个promise，但没有return出来，那这个内部的promise跟外部的链是分离的，内部promise链执行报错，外面的catch捕获不到。如果内部promise自己没有catch，那就崩了
	

```javascript
new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve('111')
    }, 1000);
}).then((res) => {
    console.log('res', res)
    // 这个内部的 promise 就跟外部的 promise 链失去联系了
    // 应该return 出去
    new Promise((resolve, reject) => {
        reject('222')
    })
}).catch((error) => {
    console.log('error', error)
})

/**
 * res, 111
 */
```

- 如何主动取消一个 promise

所谓的取消一个promise 是不准确的。在 es6中，promise本身就是没设计成可取消的。**所谓的取消都是技巧性的**。

- promise创建并行任务队列.js

- 对任务执行最大执行次数，这么些次数都不成功，那就失败。只要这么多次有一次成功那就成功

  > promise最大尝试执行次数：面试点/test6.js


# async/await

## 使用起来要特别注意的地方

- async/await 配对出现，await 一定要外层包在async里。

  - await 正常使用时后面跟个返回promise的方法
  - 但await 后面不是非要加这种方法，跟个字符串，普通方法也行，不会报错

- 外面要包上try...catch。在promise里有catch可以拦截错误，async/await 也要包裹起来才能处理错误.

  > 错误一定要处理，否则极有可能导致程序崩溃

- async/await 和 promise 混在一起用

## 跟 promise 都是异步处理，对比起来有什么特点

```javascript
// 加了await，那bb等来的就是promise链的执行结果，它就是个值
// 如果不加，bb就是个promise实例

async function ab() {
    let bb = await Promise.reject(1).catch(error => {
        console.log('error', error)
    })
    console.log(bb, bb instanceof Promise);
 }


 ab()
```

